[SPRINT 255][MOB-1533][Android SDK] Kotlin Serialization Module - User
fattmerchantorg/fattmerchant-android-sdk pull request #78
Opened 2023-01-23 13:03 UTC by cjae

## **[Ticket MOB-1533](https://fattmerchant.atlassian.net/browse/MOB-1533)**
> **Kotlin Serialization Module - User**
## What did I do?
* Create a User model using Kotlin serialization
* Create Unit test 
* Clean test folder structure
---

## Testing
* UserTest.kt
---

## Deployment/Dependency Checklist:

* [ ] [List_out_any_new_ENV_vars]
* [ ] [List_out_any_back_end_dependencies]
---
## PR notes contain:
* [ ] Checklist for any deployment dependencies (such as new env vars, back-end dependencies, etc)
## PR Checklist:
* [ ] **I tested this**
* [x] I updated from the base branch (usually `latest`)
* [ ] I attached screenshot(s) (if there were UI changes)
* [x] I used the following PR title format: "[SPRINT-XX][fat-xx] BLAH"
  * Add "[EFS]" to the PR title if it was in the ticket title, e.g. "[SPRINT-XX][fat-xx][EFS]"
* [x] I looked over the Files Changed tab
* [ ] I consulted with the ticket's product owner (if necessary)
* [x] I requested a peer review

2023-01-24 10:15 UTC, muryno commented on api/src/main/java/com/staxpayments/api/models/User.kt
> +)
lint this part, you can run ktlint on the file till @thomasvidas  enforce the linting

2023-01-24 20:40 UTC, thomasvidas requested changes
A few naming changes and one type change. Overall, this is good!

2023-01-24 20:40 UTC, thomasvidas commented on api/src/main/java/com/staxpayments/api/models/User.kt
> +    val options: String?,
Change the type to `JsonElement?`

2023-01-25 12:15 UTC, muryno commented on api/src/test/java/com/staxpayments/api/models/UserTest.kt
> +package com.staxpayments.api.models
We done need a test case for a data class, unit test is to test a logic  @cjae

2023-01-25 18:29 UTC, merged