[SPRINT-256][MOB-1503][Android SDK] API Client - Read Merchants
fattmerchantorg/fattmerchant-android-sdk pull request #91
Opened 2023-02-13 02:39 UTC by cjae

## **[Ticket MOB-1503](https://fattmerchant.atlassian.net/browse/MOB-1503)**
> ** API Client - Read Merchants**
## What did I do?
* Created a repository for Merchant
* Created Unit test 
---

## Testing
* MerchantRepositoryTest.kt
---

## Deployment/Dependency Checklist:

* [ ] [List_out_any_new_ENV_vars]
* [ ] [List_out_any_back_end_dependencies]
---
## PR notes contain:
* [ ] Checklist for any deployment dependencies (such as new env vars, back-end dependencies, etc)
## PR Checklist:
* [ ] **I tested this**
* [x] I updated from the base branch (usually `latest`)
* [ ] I attached screenshot(s) (if there were UI changes)
* [x] I used the following PR title format: "[SPRINT-XX][fat-xx] BLAH"
  * Add "[EFS]" to the PR title if it was in the ticket title, e.g. "[SPRINT-XX][fat-xx][EFS]"
* [x] I looked over the Files Changed tab
* [ ] I consulted with the ticket's product owner (if necessary)
* [x] I requested a peer review

2023-02-13 11:21 UTC, muryno requested changes

2023-02-13 11:21 UTC, muryno commented on api/src/test/java/com/staxpayments/api/datasource/MerchantRepositoryTest.kt
> +            BDDMockito.given(
remove static import 
BDDMockito.given(

to 

given(

2023-02-14 11:36 UTC, muryno approved these changes

2023-02-14 14:39 UTC, thomasvidas commented
Fix the conflicts and this looks good!

2023-02-14 14:52 UTC, merged